const CHARACTERS = [
  {
    id: 1,
    name: "amber",
    day: ["mon", "thu", "sun"],
    region: "mondsteadt",
    book: "freedom",
  },
  {
    id: 2,
    name: "barbara",
    day: ["mon", "thu", "sun"],
    region: "mondsteadt",
    book: "freedom",
  },
  {
    id: 3,
    name: "klee",
    day: ["mon", "thu", "sun"],
    region: "mondsteadt",
    book: "freedom",
  },
  {
    id: 4,
    name: "bennett",
    day: ["tue", "fri", "sun"],
    region: "mondsteadt",
    book: "resistance",
  },
  {
    id: 5,
    name: "diluc",
    day: ["tue", "fri", "sun"],
    region: "mondsteadt",
    book: "resistance",
  },
  {
    id: 6,
    name: "jean",
    day: ["tue", "fri", "sun"],
    region: "mondsteadt",
    book: "resistance",
  },
  {
    id: 7,
    name: "fisch",
    day: ["wed", "sat", "sun"],
    region: "mondsteadt",
    book: "ballad",
  },
  {
    id: 8,
    name: "kaeya",
    day: ["wed", "sat", "sun"],
    region: "mondsteadt",
    book: "resistance",
  },
  {
    id: 9,
    name: "lisa",
    day: ["wed", "sat", "sun"],
    region: "mondsteadt",
    book: "resistance",
  },
  {
    id: 10,
    name: "ningguang",
    day: ["mon", "thu", "sun"],
    region: "liyue",
    book: "prosperity",
  },
  {
    id: 11,
    name: "keqing",
    day: ["mon", "thu", "sun"],
    region: "liyue",
    book: "prosperity",
  },
  {
    id: 12,
    name: "qiqi",
    day: ["mon", "thu", "sun"],
    region: "liyue",
    book: "prosperity",
  },
  {
    id: 13,
    name: "chongyun",
    day: ["tue", "fri", "sun"],
    region: "liyue",
    book: "dilligence",
  },
  {
    id: 14,
    name: "xiangling",
    day: ["tue", "fri", "sun"],
    region: "liyue",
    book: "dilligence",
  },
  {
    id: 15,
    name: "ganyu",
    day: ["tue", "fri", "sun"],
    region: "liyue",
    book: "dilligence",
  },
  {
    id: 16,
    name: "beidou",
    day: ["wed", "sat", "sun"],
    region: "liyue",
    book: "gold",
  },
  {
    id: 17,
    name: "xingqiu",
    day: ["wed", "sat", "sun"],
    region: "liyue",
    book: "gold",
  },
  {
    id: 18,
    name: "zhongli",
    day: ["wed", "sat", "sun"],
    region: "liyue",
    book: "gold",
  },
];
export default CHARACTERS;
